//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SR", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;The following email was sent to you by PycoGroup.&lt;/h1&gt;&lt;br /&gt;&lt;p&gt;Apparently, you needed OTP to chat with PycoBot- So here it is: &lt;br /&gt;OTP:&lt;b&gt;{0}&lt;/b&gt;&lt;br /&gt;.
        /// </summary>
        internal static string EmailOTP {
            get {
                return ResourceManager.GetString("EmailOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your OTP to authorise with PycoGroup team.
        /// </summary>
        internal static string EmailSubject {
            get {
                return ResourceManager.GetString("EmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, I am Pyco Bot..
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You OTP is not correct or expired.Please send me your Pyco email again.I will send you new OTP..
        /// </summary>
        internal static string OTPInvalid {
            get {
                return ResourceManager.GetString("OTPInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your {0}, and give us OTP for authorization.This OTP will be expired in 1 hour..
        /// </summary>
        internal static string OTPSend {
            get {
                return ResourceManager.GetString("OTPSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulation.You are authorized with Pyco Bot.Now you can ask anything about Pyco Group.\n\n..
        /// </summary>
        internal static string OTPValid {
            get {
                return ResourceManager.GetString("OTPValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You OTP is not correct. Please input again..
        /// </summary>
        internal static string OTPWrong {
            get {
                return ResourceManager.GetString("OTPWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please resend your correct Pyco email address!.
        /// </summary>
        internal static string PycoEmailWrong {
            get {
                return ResourceManager.GetString("PycoEmailWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are digital consulting and software development agency.
        /// </summary>
        internal static string PycoTerm {
            get {
                return ResourceManager.GetString("PycoTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0}!.What the team are you looking for?.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Pyco Bot.
        /// </summary>
        internal static string WelcomeTilte {
            get {
                return ResourceManager.GetString("WelcomeTilte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your Pyco email address?.
        /// </summary>
        internal static string WhatEmail {
            get {
                return ResourceManager.GetString("WhatEmail", resourceCulture);
            }
        }
    }
}
